# Flight_price

## Importing Modules

In [303]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [304]:
df = pd.read_excel('flight_price.xlsx')

## Basic Information

In [305]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [306]:
df.shape

(10683, 11)

In [307]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [308]:
df.info()       # We can observe that we have no null values.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

## Checking for Null values

In [309]:
df.isnull().sum()       # We mostly have no null values.
                        # We can only see the one null value in Route and one null value in Total_Stops

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

# Feature Engineering

### Let us extract some important features from existing features

In [310]:
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [311]:
df.head()       # We can see that the columns "Date" , "Month" and "Year" are added.

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

### Now we can remove the "Date_of_Journey" column.

In [312]:
df.drop('Date_of_Journey',axis=1,inplace=True)

In [313]:
df['Year'].unique()

array(['2019'], dtype=object)

### As year column has only one value "2019". It is better to drop this column

In [314]:
df.drop("Year",axis=1,inplace=True)

In [315]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03

### We can see that the Arrival Time contains date and month also so we have to remove them and Only store the Arrival time

In [316]:
df['Arrival_Time'] = df['Arrival_Time'].str.split(" ").str[0]

In [317]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,03
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,9,06
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03

### Now split the Arrival Time and Departure Time into ArrivalTime_Hours, ArrivalTime_Hours, DepTime_Hours, DepTime_Min.

In [318]:
df['ArrivalTime_Hours'] = df['Arrival_Time'].str.split(':').str[0]
df['ArrivalTime_Min'] = df['Arrival_Time'].str.split(':').str[1]
df['DepTime_Hours'] = df['Dep_Time'].str.split(':').str[0]
df['DepTime_Min'] = df['Dep_Time'].str.split(':').str[1]

In [319]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,ArrivalTime_Hours,ArrivalTime_Min,DepTime_Hours,DepTime_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,03,01,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,9,06,04,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,21,35,16,50

### Now we can drop the Arrival_Time and Dep_Time

In [320]:
df.drop(['Dep_Time','Arrival_Time'],axis=1,inplace=True)

In [321]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,ArrivalTime_Hours,ArrivalTime_Min,DepTime_Hours,DepTime_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,03,01,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,05,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,06,04,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,05,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,01,03,21,35,16,50

### The route is also not required so that is not a important column

In [322]:
df.drop("Route",axis=1,inplace=True)

In [323]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,ArrivalTime_Hours,ArrivalTime_Min,DepTime_Hours,DepTime_Min
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,No info,3897,24,03,01,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2 stops,No info,7662,1,05,13,15,05,50
2,Jet Airways,Delhi,Cochin,19h,2 stops,No info,13882,9,06,04,25,09,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,No info,6218,12,05,23,30,18,05
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,No info,13302,01,03,21,35,16,50

### Coverting the Duration into minutes

In [324]:
df['Duration'].unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m'],
      dtype=object)

In [325]:
def func(x):
    h=0
    m=0
    part = 0
    if 'h' in x:
        h=int(x.split('h')[0])
    
    if 'm' in x:
        part = x.split('h')[-1].replace('m','').strip()

    if part :
        m=int(part)

    return h*60 + m
df['Duration'] = df['Duration'].apply(func)

In [326]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,ArrivalTime_Hours,ArrivalTime_Min,DepTime_Hours,DepTime_Min
0,IndiGo,Banglore,New Delhi,170,non-stop,No info,3897,24,03,01,10,22,20
1,Air India,Kolkata,Banglore,445,2 stops,No info,7662,1,05,13,15,05,50
2,Jet Airways,Delhi,Cochin,1140,2 stops,No info,13882,9,06,04,25,09,25
3,IndiGo,Kolkata,Banglore,325,1 stop,No info,6218,12,05,23,30,18,05
4,IndiGo,Banglore,New Delhi,285,1 stop,No info,13302,01,03,21,35,16,50

### Now let us the fill the values of Total Stops in numbers(0,1,2,3,4)

In [327]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [328]:
df['Total_Stops'].replace({
    np.nan : 1,
    "1 stop" :  1,
    "non-stop": 0,
    "2 stops" : 2,
    "3 stops" : 3,
    "4 stops" : 4
},inplace=True)

In [329]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,ArrivalTime_Hours,ArrivalTime_Min,DepTime_Hours,DepTime_Min
0,IndiGo,Banglore,New Delhi,170,0,No info,3897,24,03,01,10,22,20
1,Air India,Kolkata,Banglore,445,2,No info,7662,1,05,13,15,05,50
2,Jet Airways,Delhi,Cochin,1140,2,No info,13882,9,06,04,25,09,25
3,IndiGo,Kolkata,Banglore,325,1,No info,6218,12,05,23,30,18,05
4,IndiGo,Banglore,New Delhi,285,1,No info,13302,01,03,21,35,16,50

In [330]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Airline            10683 non-null  object
 1   Source             10683 non-null  object
 2   Destination        10683 non-null  object
 3   Duration           10683 non-null  int64
 4   Total_Stops        10683 non-null  int64
 5   Additional_Info    10683 non-null  object
 6   Price              10683 non-null  int64
 7   Date               10683 non-null  object
 8   Month              10683 non-null  object
 9   ArrivalTime_Hours  10683 non-null  object
 10  ArrivalTime_Min    10683 non-null  object
 11  DepTime_Hours      10683 non-null  object
 12  DepTime_Min        10683 non-null  object
dtypes: int64(3), object(10)
memory usage: 1.1+ MB

###  Now convert the columns into int type

In [331]:
df['Total_Stops'] = df['Total_Stops'].astype(int)
df['Date'] = df['Date'].astype(int)
df['Month'] = df['Month'].astype(int)
df['ArrivalTime_Min'] = df['ArrivalTime_Min'].astype(int)
df['DepTime_Min'] = df['DepTime_Min'].astype(int)
df['DepTime_Hours'] = df['DepTime_Hours'].astype(int)
df['ArrivalTime_Hours'] = df['ArrivalTime_Hours'].astype(int)

In [332]:
df

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,ArrivalTime_Hours,ArrivalTime_Min,DepTime_Hours,DepTime_Min
0,IndiGo,Banglore,New Delhi,170,0,No info,3897,24,3,1,10,22,20
1,Air India,Kolkata,Banglore,445,2,No info,7662,1,5,13,15,5,50
2,Jet Airways,Delhi,Cochin,1140,2,No info,13882,9,6,4,25,9,25
3,IndiGo,Kolkata,Banglore,325,1,No info,6218,12,5,23,30,18,5
4,IndiGo,Banglore,New Delhi,285,1,No info,13302,1,3,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,150,0,No info,4107,9,4,22,25,19,55
10679,Air India,Kolkata,Banglore,155,0,No info,4145,27,4,23,20,20,45
10680,Jet Airways,Banglore,Delhi,180,0,No info,7229,27,4,11,20,8,20
10681,Vistara,Banglore,New Delhi,160,0,No info,12648,1,3,14,10,11,30
10682,Air India,Delhi,Cochin,500,2,No info,11753,9,5,19,15,10,55

### "Additional_Info" Column is also not much important

In [333]:
df.drop('Additional_Info',axis=1,inplace=True)

In [334]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Airline            10683 non-null  object
 1   Source             10683 non-null  object
 2   Destination        10683 non-null  object
 3   Duration           10683 non-null  int64
 4   Total_Stops        10683 non-null  int64
 5   Price              10683 non-null  int64
 6   Date               10683 non-null  int64
 7   Month              10683 non-null  int64
 8   ArrivalTime_Hours  10683 non-null  int64
 9   ArrivalTime_Min    10683 non-null  int64
 10  DepTime_Hours      10683 non-null  int64
 11  DepTime_Min        10683 non-null  int64
dtypes: int64(9), object(3)
memory usage: 1001.7+ KB

### The different Airlines

In [335]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

### Source of  the flights

In [336]:
df['Source'].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

### Destination of the flights

In [337]:
df['Destination'].unique()

array(['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

In [338]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops', 'Price',
       'Date', 'Month', 'ArrivalTime_Hours', 'ArrivalTime_Min',
       'DepTime_Hours', 'DepTime_Min'],
      dtype='object')

# Final Dataframe

In [339]:
df

,Airline,Source,Destination,Duration,Total_Stops,Price,Date,Month,ArrivalTime_Hours,ArrivalTime_Min,DepTime_Hours,DepTime_Min
0,IndiGo,Banglore,New Delhi,170,0,3897,24,3,1,10,22,20
1,Air India,Kolkata,Banglore,445,2,7662,1,5,13,15,5,50
2,Jet Airways,Delhi,Cochin,1140,2,13882,9,6,4,25,9,25
3,IndiGo,Kolkata,Banglore,325,1,6218,12,5,23,30,18,5
4,IndiGo,Banglore,New Delhi,285,1,13302,1,3,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,150,0,4107,9,4,22,25,19,55
10679,Air India,Kolkata,Banglore,155,0,4145,27,4,23,20,20,45
10680,Jet Airways,Banglore,Delhi,180,0,7229,27,4,11,20,8,20
10681,Vistara,Banglore,New Delhi,160,0,12648,1,3,14,10,11,30
10682,Air India,Delhi,Cochin,500,2,11753,9,5,19,15,10,55

In [340]:
df.to_csv("cleaned_dataset.csv",index=False)